name: Bun Build

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Bun 
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
      
      - name: Build project
        run: bun run build

      - name: Tidy up
        run: |
          rm -rf ./.git

      - name: Compress artifact
        run: tar cpJf ./charles-blog2.tar.xz .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: target-archive
          path: ./charles-blog2.tar.xz

  deployment:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: target-archive

      - name: Send artifact to server(s)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "./charles-blog2.tar.xz"
          target: /home/${{ secrets.USER }}/

      - name: Deploy project on server(s)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /opt/charles-blog2
            sudo mv -f ~/charles-blog2.tar.xz .
            sudo systemctl stop charlesblog
            sudo rm -rf ./charles-blog2
            sudo mkdir ./charles-blog2
            cd ./charles-blog2
            sudo tar xpJf ../charles-blog2.tar.xz
            sudo chown -R charles-blog2:charles-blog2 .
            sudo systemctl start charlesblog
